# Generated by Django 4.0.4 on 2022-05-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/images')),
                ('serviceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.serviceprovider')),
            ],
        ),
    ]
