# Generated by Django 4.0.4 on 2022-06-03 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='guestCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='party',
            name='locationLatitude',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='locationLongitude',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
