# Generated by Django 4.0.4 on 2022-06-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_party_guestcount_party_locationlatitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='pendingCost',
        ),
    ]
