# Generated by Django 4.0.4 on 2022-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_party_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='provider',
        ),
        migrations.AddField(
            model_name='party',
            name='catering',
            field=models.ManyToManyField(null=True, to='api.serviceprovider'),
        ),
    ]
