# Generated by Django 4.0.4 on 2022-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partythemeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.AddField(
            model_name='contentmaker',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
