# Generated by Django 4.0.4 on 2022-05-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fooditem_foodimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('decorator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='api.decorator')),
            ],
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.fooditem'),
        ),
        migrations.CreateModel(
            name='ThemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/themeimage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.theme')),
            ],
        ),
    ]
