# Generated by Django 4.0.4 on 2022-06-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_party_pendingcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMakerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('contentmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentmaker')),
            ],
        ),
        migrations.CreateModel(
            name='PartyContentMakerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentmakerslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partycontentmakerslot', to='api.contentmakerslot')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partycontentmakerslot', to='api.party')),
            ],
        ),
    ]
