# Generated by Django 4.0.4 on 2022-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contentmakerslot_partycontentmakerslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
