# Generated by Django 4.0.4 on 2022-05-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_party_catering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='partyTime',
        ),
    ]
