# Generated by Django 4.0.4 on 2022-05-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_party_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='pendingCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
