# Generated by Django 4.0.4 on 2022-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_party_pendingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(default='unconfirmed', max_length=255),
        ),
    ]
