# Generated by Django 4.0.4 on 2022-06-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_payment_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.party')),
                ('serviceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.serviceprovider')),
            ],
        ),
    ]
