# Generated by Django 4.0.4 on 2022-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
