# Generated by Django 4.0.4 on 2022-05-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_party_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.party'),
        ),
    ]
