# Generated by Django 4.0.4 on 2022-05-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_foodcart_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcartitem',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcartitem', to='api.fooditem'),
        ),
    ]
