# Generated by Django 4.0.4 on 2022-06-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_decorator_price_partyvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partycatering', to='api.catering')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partycatering', to='api.party')),
            ],
        ),
    ]
