# Generated by Django 4.0.4 on 2022-05-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_foodcartitem_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.party'),
        ),
        migrations.AlterField(
            model_name='foodcartitem',
            name='foodcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcartitem', to='api.foodcart'),
        ),
        migrations.AlterField(
            model_name='foodcartitem',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fooditem'),
        ),
    ]
