# Generated by Django 4.0.4 on 2022-05-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_foodcart_party_alter_foodcartitem_foodcart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
        ),
    ]
