# Generated by Django 4.0.4 on 2022-06-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_partydecorator_catering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyContentMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partycontentmaker', to='api.contentmaker')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partycontentmaker', to='api.party')),
            ],
        ),
    ]
