# Generated by Django 4.0.4 on 2022-06-06 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_partycontentmaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='locationLatitude',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.810300000000001574562702444382011890411376953125'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='party',
            name='locationLongitude',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.412499999999994315658113919198513031005859375'), max_digits=5),
        ),
    ]
