# Generated by Django 4.0.4 on 2022-05-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_partyvenueslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyvenueslot',
            name='status',
        ),
    ]
