# Generated by Django 4.0.4 on 2022-06-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_party_locationlatitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcartitem',
            name='Catering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catering'),
        ),
    ]
