# Generated by Django 4.0.4 on 2022-05-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_partyvenueslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyvenueslot',
            name='venueslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.venueslot'),
        ),
    ]
