# Generated by Django 4.0.4 on 2022-05-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_partyvenueslot_venueslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcart', to='api.party'),
        ),
    ]
