# Generated by Django 4.0.4 on 2022-06-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_foodcartitem_catering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcartitem',
            old_name='Catering',
            new_name='catering',
        ),
    ]
