# Generated by Django 4.0.4 on 2022-06-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_contentmaker_price_alter_decorator_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
