# Generated by Django 4.0.4 on 2022-05-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_foodcart_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodcart', to='api.party'),
        ),
        migrations.AlterField(
            model_name='partyvenueslot',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venueslot', to='api.party'),
        ),
    ]
