# Generated by Django 4.0.4 on 2022-05-31 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_partyvenueslot_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyvenueslot',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partyvenueslot', to='api.party'),
        ),
    ]
