# Generated by Django 4.0.4 on 2022-05-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_partyvenueslot_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcart', to='api.party'),
        ),
        migrations.AlterField(
            model_name='partyvenueslot',
            name='venueslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partyvenueslot', to='api.venueslot'),
        ),
    ]
