# Generated by Django 4.0.4 on 2022-05-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_foodcart_party_alter_partyvenueslot_venueslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodcart', to='api.party'),
        ),
    ]
